### PR TITLE
Add an optional callback to runAsync() to be notified when a check finished.

### PR DESCRIPTION
**Pull request by zigmo**
e.g.:

```ts
import * as notifier from 'node-notifier'
//...
this._checker.runAsync((errors: number) => {
            if (errors > 0) {
                notifier.notify({
                    'title': 'Typescript-Error',
                    'message': 'Check the console output'
                });
            } else {
                notifier.notify({
                    'title': 'Typescript-OK',
                    'message': 'No errors found'
                });
            }
        });
```

### CODE REVIEW

**Comment by vegarringdal** [comment]
thx, Ill have a look on it later today 👍

**Comment by vegarringdal** [comment]
And btw, could you update the readme showing its a optional callback there :-)

**Comment by vegarringdal** [comment]
@zigmo 
Just tested look great

There is some tslint errors, and killing worker is printed twice..
image

maybe move the callback down and use if/else
````typescript
private createThread(callback?: (errors: number) => void): void {

        // create worker fork
        this.worker = child.fork(path.join(__dirname, 'worker.js'), []);

        // listen for worker messages
        this.worker.on('message', (msg: any) => {



            if (msg === 'error') {

                // if error then exit
                this.writeText('error typechecker');
                process.exit(1);
            } else {
                // callback if correct type else just call kill worker
                if (callback && msg && typeof msg === 'object' && msg.type === 'result') {
                    callback(msg.result);
                } else {
                    // if not error, then just kill worker
                    this.writeText('killing worker');
                    this.killWorker();
                }
            }
        });
    }
```




And like I said earlier, great if u can add somthing to the readme file also

**Comment by zigmo** [comment]
@vegarringdal 
Oh, did't see this - thanks for pointing me in the right direction.  I had just some errors in the worker (was new for me that send in process.send is optional). Will check and fix them all and update this PR. Thanks for reviewing.

**Comment by zigmo** [comment]
@vegarringdal 
Hope I could fix everything and not introduced any new problems. Maybe you can take an other look.
I removed the introduced push-commans and added this as a option to the already existing command. Makes more sence to me.

**Comment by vegarringdal** [comment]
@zigmo 
I just tried it
Looks like its broken atm, I wont have time to look into the code before tomorrow.
It looks like few parts are broken, process is not getting killed, and callback is never called

To reproduce my errors do I did this:

I un-commented the last 2 lines in the `test.ts` (under /src... not the test.js under root)
And used double quotes in the path 
This will then produce 2 ts errors and 1 tslint error
```
// just to get a few errors
import * as child from 'child_process';
import * as path from "path";
```


Then I edited the test.js to include a callback

```javascript
var path = require('path')

//get typehelper (use built source)
var TypeHelper = require('./dist/commonjs/index.js').TypeHelper

var checker = TypeHelper({
    tsConfig: './tsconfig.json',
    basePath: './',
    tsLint: './tslint.json',
    name: 'Test'
});

var doTypeCheck = async() => {

    //let totalErrors = checker.runSync();
    let totalErrors = await checker.runPromise();
    console.log(totalErrors)
}



// options are (need to test all by them self before release)
// doTypeCheck();
// checker.runSync()
 checker.runAsync((x)=>{
     console.log('\nfound errors:x')
 });
// checker.runWatch('./src')
```


image

**Comment by zigmo** [comment]
Odd .. will check this.

**Comment by vegarringdal** [comment]
hmm, I might have downloaded before you did 2 dist build..

**Comment by vegarringdal** [comment]
@zigmo 

Let me give it a new try, incase Ive messed up and tried it before you said u where ready

**Comment by zigmo** [comment]
with

```ts
checker.runAsync((x)=>{
    console.log(`\nfound errors:${x}`);
});
```

This is my local output:

Typechecker plugin(async) :Test Sync.
Time:Sun Sep 03 2017 23:16:11 GMT+0200 (W. Europe Summer Time)

File errors:
└── C:/Users/SergejLoch/Source/Repos/GitHub/fuse-box-typechecker/src/test.ts (3,17) (Error:TS1005) 'from' expected.
└── C:/Users/SergejLoch/Source/Repos/GitHub/fuse-box-typechecker/src/test.ts (3,21) (Error:TS1005) ';' expected.
└── C:/Users/SergejLoch/Source/Repos/GitHub/fuse-box-typechecker/src/test.ts (3,26) (Error:TS1005) ';' expected.
└── C:/Users/SergejLoch/Source/Repos/GitHub/fuse-box-typechecker/src/test.ts (3,14) (Error:TS6133) 'ch' is declared but never used.
└── C:/Users/SergejLoch/Source/Repos/GitHub/fuse-box-typechecker/src/test.ts (3,17) (Error:TS1141) String literal expected.
└── C:/Users/SergejLoch/Source/Repos/GitHub/fuse-box-typechecker/src/test.ts (3,21) (Error:TS2304) Cannot find name 'from'.
└── C:/Users/SergejLoch/Source/Repos/GitHub/fuse-box-typechecker/src/test.ts (4,14) (Error:TS6133) 'path' is declared but never used.
└── C:/Users/SergejLoch/Source/Repos/GitHub/fuse-box-typechecker/src/test.ts (3,21) (Error:no-unused-expression) unused expression, expected an assignment or function call
└── C:/Users/SergejLoch/Source/Repos/GitHub/fuse-box-typechecker/src/test.ts (3,26) (Error:no-unused-expression) unused expression, expected an assignment or function call
└── C:/Users/SergejLoch/Source/Repos/GitHub/fuse-box-typechecker/src/test.ts (3,20) (Error:semicolon) Missing semicolon
└── C:/Users/SergejLoch/Source/Repos/GitHub/fuse-box-typechecker/src/test.ts (3,25) (Error:semicolon) Missing semicolon

Errors:11
└── Options: 0
└── Global: 0
└── Syntactic: 3
└── Semantic: 4
└── TsLint: 4

Typechecking time: 2611ms
Quiting typechecker

killing worker
found errors:11

**Comment by vegarringdal** [comment]
yes, I tested to soon

**Comment by zigmo** [comment]
Glad its working.

**Comment by vegarringdal** [comment]
I really need to add more testing to this, but a lot is visual to, so some parts cant be fully automated..

**Comment by vegarringdal** [comment]
thx for you help

**Pull request merged**
