### PR TITLE
Fix spelling issues

### PR DESCRIPTION
**Pull request by dlannoye**
I noticed some spelling mistakes in the logs that were annoying for myself and others on my team to see during build. Here are fixes for these issues.

### CODE REVIEW

**Comment by vegarringdal** [comment]
Great thanks
Ill try and get a new release out very soon.
Been using it a lot ?

**Comment by dlannoye** [comment]
Yes, I have several projects that are building using fuse-box and fuse-box-typechecker. It's been pretty good for how we are using it. One change I might looking into making for I would like to be able to get the type checker results from the plugin rather then just a list of errors so I can better integrate this it to the broader build for our product.

**Comment by vegarringdal** [comment]
We could add some option for this, tell me more what you are thinking in a issue etc.

Im adding small helper functions so its easier to use with thread checking without using internal function.

Using it for emitting distribution code for modules is nice too.
https://github.com/mframejs/mframejs/blob/master/build.js

Actually considering using 1 version lower of the type checker instead of gulp, would really clean up the build script a lot

**Comment by vegarringdal** [comment]
fuse-box-typechecker@2.9.0 released

**Comment by vegarringdal** [comment]
@dlannoye 

About getting the results
Getting a object like this would help (Ive just use console.log(result) in picture under

result without errors
image

one with 2 simple errors
image

**Comment by vegarringdal** [comment]
more info here, also pushing next version if I add stuff so people have a chance to test I havent added anything that will break
https://github.com/fuse-box/fuse-box-typechecker/issues/52

**Comment by dlannoye** [comment]
Yes, that is very close to what I was thinking would be nice. I might still be nice to have a error count to check for backwards compatibility, but then having this additional information to log out. This would probably be a breaking change for the return type of `runAsync`, `runPromise` and `runSync`

**Comment by vegarringdal** [comment]
Atm its in `fuse-box-typechecker@next` (2)
Its own sync function only `.checkSyncReturnObj()`, made it fo there is a option to get all results (this is almost unedited results, like typescript and tslint gives em)

Where/how was the plan to use this information ?

**Comment by dlannoye** [comment]
I personally wanted it with the async or promise version. My plan was to then take the information and use it in my broader build system to surface the errors in the same manner that we do for other build tasks. Currently without the more detailed errors I have to resort to just having that part of the build log a general error that says something has failed to and scroll up in the logs to find more information. With the additional result information I can log more actionable messages here.

**Comment by dlannoye** [comment]
BTW, Thanks for looking into this. I really appreciate it.

**Comment by vegarringdal** [comment]
Let me have a look to see if I can add the one with promise

**Comment by vegarringdal** [comment]
if you have time you can try `.checkSyncReturnObj()` when u have time
if you have any ideas how you would want result object to look like then please make a simple function to parse it and simplify it and test if with JSON.stringify, if it works then u save a a lot of time I dont have much of this week :-)

**Comment by dlannoye** [comment]
I can try to take a look at this in a few hours and give you some feedback. I can also take a look at how to get the results serialize between threads too.

**Comment by vegarringdal** [comment]
Great

Pretty much just need to get in some code here to serialize the result obj
https://github.com/fuse-box/fuse-box-typechecker/blob/master/src/worker.ts#L38-L39

Then everything else is done.
`node build` is the new command for building new dist. removed gulp, its using version 2.9.0 for transpiling its own code now 😂

**Comment by vegarringdal** [comment]
using it as transpiler is better too, since it wont by default emit code that have ts or lint errors :-)

**Pull request merged**
