### PR TITLE
Adding JSON5 support

### PR DESCRIPTION
**Pull request by joshball**
Typescript allows comments and trailing commas in tsconfig and tslint allows comments.
The current library uses the default require for loading JSON, which fails with either.
Added the JSON5 library, and overwrote the .json extension to use it.

### CODE REVIEW

**Comment by vegarringdal** [comment]
Thx, Ill have a look at this later today 😁

**Comment by vegarringdal** [comment]
version 2.12.0 released, thx

**Comment by joshball** [comment]
Outstanding. Thank you. And nice work. ;-)

**Comment by vegarringdal** [comment]
Hopefully Ill get some more time to improve it.
Also need to look into changes coming to tslint, it will be part of eslint.

**Pull request merged**
