### PR TITLE
Update interfaces.ts

### PR DESCRIPTION
**Pull request by jpike88**
Make arguments optional

### CODE REVIEW

**Comment by jpike88** [comment]
@vegarringdal also please publish when you get a chance! ty

**Comment by vegarringdal** [comment]
I can have a look tonight or tomorrow.
Did you look at that other issue where I asked you to have a check/make PR on changes you wanted ?

**Comment by jpike88** [comment]
That change you did is enough actually, have tested it and it works well. Am happy just for this one to be merged and a release done

**Comment by vegarringdal** [comment]
@jpike88 

released 3.1.1... yes it should have been 3.1.0 😂

**Pull request merged**
